spring:
  docker:
    compose:
      enabled: true
      file: wishlist/compose.yml
      lifecycle-management: start-only
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      modify-topic-configs: true
  application:
    name: "wishlist"
  datasource:
    url: jdbc:postgresql://localhost:9911/wishdb
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 9921
      password: RDSpassword
server:
  port: 8001
iwag:
  services:
    price:
      kafka-topic: newWishes
