spring:
  application:
    name: mail-service
  kafka:
    consumer:
      group-id: mail-service
    bootstrap-servers: localhost:9092

postbox:
  endpoint: ${POSTBOX_ENDPOINT:https://postbox.cloud.yandex.net}
  region: ${POSTBOX_REGION:ru-central1}
  access-key: ${POSTBOX_ACCESS_KEY}
  secret-key: ${POSTBOX_SECRET_KEY}
  from: ${POSTBOX_FROM:noreply@iwantagift.online}

server:
  port: 9978
