CREATE TABLE refresh_tokens
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              UUID        NOT NULL,
    token_hash           TEXT        NOT NULL UNIQUE,
    issued_at            TIMESTAMPTZ NOT NULL,
    expires_at           TIMESTAMPTZ NOT NULL,
    revoked_at           TIMESTAMPTZ,
    replaced_by_token_id BIGINT,
    CONSTRAINT refresh_tokens_replaced_by_fk
        FOREIGN KEY (replaced_by_token_id) REFERENCES refresh_tokens (id),
    CONSTRAINT refresh_tokens_user_id_fk FOREIGN KEY (user_id) REFERENCES accounts (id)
);