spring:
  docker:
    compose:
      enabled: true
      file: auth/compose.yml
      lifecycle-management: start-only
  application:
    name: "auth"
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8091
  kafka:
    bootstrap-servers: localhost:9094
  datasource:
    url: jdbc:postgresql://localhost:9912/auth
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 9922
      password: RDSpassword
server:
  port: 8091
iwag:
  services:
    wishlist:
      kafka-topics:
        - createdUser
        - deletedUser
    profile:
      kafka-topics:
        - createdUser
