spring:
  config:
    import: classpath:application.yaml
  application:
    name: ${SPRING_APPLICATION_NAME:auth}

iwag:
  ui-base-url: ${IWAG_UI_BASE_URL}
  services:
    wishlist:
      kafka-topics: ${IWAG_WISHLIST_KAFKA_TOPICS:accountEvent}
    profile:
      kafka-topics: ${IWAG_PROFILE_KAFKA_TOPICS:createdUser}
    mail:
      kafka-topics: ${IWAG_MAIL_KAFKA_TOPICS:emailChange,emailVerify,passwordReset,passwordResetRequest}
