spring:
  application:
    name: "ui"
  security:
    oauth2:
      client:
        registration:
          iwag-ui:
            provider: iwag-auth
            client-id: iwag-ui
            client-secret: dev-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
        provider:
          iwag-auth:
            issuer-uri: http://localhost:8091
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

server:
  port: 8080

iwag:
  services:
    auth:
      url: localhost:8091
      use-https: false
    wishlists:
      url: localhost:8001
      use-https: false
    profile:
      url: localhost:8002
      use-https: false

