spring:
  application:
    name: "ui"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

server:
  port: 8080

iwag:
  services:
    auth:
      url: localhost:8091
      use-https: false
    wishlists:
      url: localhost:8001
      use-https: false
    profile:
      url: localhost:8002
      use-https: false

jwt:
  cookie:
    name:
      access: "IWAG-ACCESS-COOKIE"
      refresh: "IWAG-REFRASH-COOKIE"
    max-age-seconds: 900
    set-secure: true
